### ISSUE TITLE
Hide per app rather than whole system

### ISSUE THREAD

**Issue by privacyguy123** [Xposed-Modules-Repo/io.github.alexdonh.noaccessibilityservices#2]
Is this ever a possibility?

**Comment by alexdonh** [comment]
Actually you dont really need to select System framework just untick that, only tick to apps you want and reboot. See if it works for you.

**Comment by privacyguy123** [comment]
Makes the app insta crash unfortunately, is there any explanation to this?

**Comment by alexdonh** [comment]
> Makes the app insta crash unfortunately, is there any explanation to this?

what app you were talking about? and did you try clear app data ? so far there are some apps crashing here and there but it's kinda beyond what this module does. see here https://github.com/Xposed-Modules-Repo/io.github.alexdonh.noaccessibilityservices/issues/1#issuecomment-1779424728
